# Generated by Django 4.1.1 on 2022-11-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teacher'),
        ('tau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('attendance', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(to='tau.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
