# Generated by Django 4.1.1 on 2022-11-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tau', '0003_alter_class_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
