# Generated by Django 4.1.1 on 2022-11-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tau', '0005_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
