# Generated by Django 4.1.1 on 2022-11-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tau', '0007_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
