# Generated by Django 4.1.1 on 2022-11-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tau', '0009_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
